/** @type {import('tailwindcss').Config} */
module.exports = {
  // darkMode: 'class',
  darkMode: 'class',
  mode: "light", //加在這裡
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors: {
        "jg-color-bg-bg":"var(--jg-color-bg-bg)",
        "jg-color-bg-elevated":"var(--jg-color-bg-elevated)",
        "jg-color-bg-popover":"var(--jg-color-bg-popover)",
        "jg-color-bg-strong":"var(--jg-color-bg-strong)",
        "jg-color-bg-subtle":"var(--jg-color-bg-subtle)",
        "jg-color-bg-tooltip":"var(--jg-color-bg-tooltip)",
        "jg-color-bg-button-primary-green":"var(--jg-color-bg-button-primary-green)",
        "jg-color-bg-button-primary-green-disable":"var(--jg-color-bg-button-primary-green-disable)",
        "jg-color-bg-button-primary-green-hover":"var(--jg-color-bg-button-primary-green-hover)",
        "jg-color-bg-button-primary-red":"var(--jg-color-bg-button-primary-red)",
        "jg-color-bg-button-primary-red-disable":"var(--jg-color-bg-button-primary-red-disable)",
        "jg-color-bg-button-primary-red-hover":"var(--jg-color-bg-button-primary-red-hover)",
        "jg-color-bg-button-primary-yellow":"var(--jg-color-bg-button-primary-yellow)",
        "jg-color-bg-button-primary-yellow-disable":"var(--jg-color-bg-button-primary-yellow-disable)",
        "jg-color-bg-button-primary-yellow-hover":"var(--jg-color-bg-button-primary-yellow-hover)",
        "jg-color-bg-button-warning":"var(--jg-color-bg-button-warning)",
        "jg-color-bg-input-default":"var(--jg-color-bg-input-default)",
        "jg-color-bg-input-disable":"var(--jg-color-bg-input-disable)",
        "jg-color-bg-input-focused":"var(--jg-color-bg-input-focused)",
        "jg-color-bg-tab-default":"var(--jg-color-bg-tab-default)",
        "jg-color-bg-tab-selected-green":"var(--jg-color-bg-tab-selected-green)",
        "jg-color-bg-tab-selected-red":"var(--jg-color-bg-tab-selected-red)",
        "jg-color-bg-table-list-hover-1":"var(--jg-color-bg-table-list-hover-1)",
        "jg-color-bg-table-list-hover-2":"var(--jg-color-bg-table-list-hover-2)",
        "jg-color-border-split-muted":"var(--jg-color-border-split-muted)",
        "jg-color-border-split-strong":"var(--jg-color-border-split-strong)",
        "jg-color-border-button-outline":"var(--jg-color-border-button-outline)",
        "jg-color-border-button-outline-hover":"var(--jg-color-border-button-outline-hover)",
        "jg-color-border-button-secondary":"var(--jg-color-border-button-secondary)",
        "jg-color-border-button-secondary-hover":"var(--jg-color-border-button-secondary-hover)",
        "jg-color-border-input-default":"var(--jg-color-border-input-default)",
        "jg-color-border-input-focused":"var(--jg-color-border-input-focused)",
        "jg-color-border-input-hover":"var(--jg-color-border-input-hover)",
        "jg-color-border-input-wrong":"var(--jg-color-border-input-wrong)",
        "jg-color-icon-disable":"var(--jg-color-icon-disable)",
        "jg-color-icon-general":"var(--jg-color-icon-general)",
        "jg-color-icon-green-default":"var(--jg-color-icon-green-default)",
        "jg-color-icon-green-disable":"var(--jg-color-icon-green-disable)",
        "jg-color-icon-green-subtle":"var(--jg-color-icon-green-subtle)",
        "jg-color-icon-info":"var(--jg-color-icon-info)",
        "jg-color-icon-primary":"var(--jg-color-icon-primary)",
        "jg-color-icon-red":"var(--jg-color-icon-red)",
        "jg-color-icon-warning":"var(--jg-color-icon-warning)",
        "jg-color-text-black":"var(--jg-color-text-black)",
        "jg-color-text-hight-light":"var(--jg-color-text-hight-light)",
        "jg-color-text-primary":"var(--jg-color-text-primary)",
        "jg-color-text-red-default":"var(--jg-color-text-red-default)",
        "jg-color-text-red-disable":"var(--jg-color-text-red-disable)",
        "jg-color-text-scendary":"var(--jg-color-text-scendary)",
        "jg-color-text-tooltip":"var(--jg-color-text-tooltip)",
        "jg-color-text-green-default":"var(--jg-color-text-green-default)",
        "jg-color-text-green-disable":"var(--jg-color-text-green-disable)",
        "jg-color-text-green-subtle":"var(--jg-color-text-green-subtle)",
        "jg-color-text-yellow-default":"var(--jg-color-text-yellow-default)",
        "jg-color-text-yellow-disable":"var(--jg-color-text-yellow-disable)",

      },
      spacing: {
        "jg-opacity-94":"var(--jg-opacity-94)",
        "jg-radius-sm":"var(--jg-radius-sm)",
        "jg-radius-md":"var(--jg-radius-md)",
        "jg-radius-lg":"var(--jg-radius-lg)",
      },
     
    }
  },
  plugins: [],
}
