import { extendTheme } from "@chakra-ui/react";

const theme = extendTheme({
  config: {
    useSystemColorMode: false,
    initialColorMode: "dark",
    cssVarPrefix: "chakra",
  },
  colors: {
    "jg-color-base-black": "#000000",
    "jg-color-base-white": "#ffffff",
    "jg-color-green-100": "#1ddf63",
    "jg-color-green-200": "#149c45",
    "jg-color-green-300": "#0e6d31",
    "jg-color-green-400": "#0a4c22",
    "jg-color-green-50": "#20f56d",
    "jg-color-green-500": "#073618",
    "jg-color-green-alpha-10": "#1ddf631a",
    "jg-color-green-alpha-12": "#1ddf631f",
    "jg-color-green-alpha-14": "#1ddf6324",
    "jg-color-green-alpha-16": "#1ddf6329",
    "jg-color-green-alpha-6": "#1ddf630f",
    "jg-color-green-alpha-8": "#1ddf6314",
    "jg-color-neutral-100": "#f5f5f5",
    "jg-color-neutral-200": "#e5e5e5",
    "jg-color-neutral-300": "#d4d4d4",
    "jg-color-neutral-400": "#a3a3a3",
    "jg-color-neutral-50": "#fafafa",
    "jg-color-neutral-500": "#737373",
    "jg-color-neutral-600": "#525252",
    "jg-color-neutral-700": "#404040",
    "jg-color-neutral-800": "#262626",
    "jg-color-neutral-900": "#1d1d1d",
    "jg-color-neutral-950": "#0a0a0a",
    "jg-color-red-100": "#ed416a",
    "jg-color-red-200": "#a62e4a",
    "jg-color-red-300": "#742034",
    "jg-color-red-400": "#511624",
    "jg-color-red-50": "#ff4875",
    "jg-color-red-500": "#391019",
    "jg-color-red-alpha-10": "#ed416a1a",
    "jg-color-red-alpha-12": "#ed416a1f",
    "jg-color-red-alpha-14": "#ed416a24",
    "jg-color-red-alpha-16": "#ed416a29",
    "jg-color-red-alpha-6": "#ed416a0f",
    "jg-color-red-alpha-8": "#ed416a14",
    "jg-color-white-alpha-12": "#ffffff1f",
    "jg-color-white-alpha-16": "#ffffff29",
    "jg-color-white-alpha-2": "#ffffff05",
    "jg-color-white-alpha-4": "#ffffff0a",
    "jg-color-white-alpha-8": "#ffffff14",
    "jg-color-yellow-100": "#e9fe53",
    "jg-color-yellow-200": "#a3b23a",
    "jg-color-yellow-300": "#727c29",
    "jg-color-yellow-400": "#50571c",
    "jg-color-yellow-50": "#ffff5b",
    "jg-color-yellow-500": "#383d14",
    "jg-color-yellow-alpha-10": "#e9fe531a",
    "jg-color-yellow-alpha-12": "#e9fe531f",
    "jg-color-yellow-alpha-14": "#e9fe5324",
    "jg-color-yellow-alpha-16": "#e9fe5329",
    "jg-color-yellow-alpha-6": "#e9fe530f",
    "jg-color-yellow-alpha-8": "#e9fe5314",
  },
  spacing: {
    "jg-dimensions-2": "0.125rem",
    "jg-dimensions-4": "0.25rem",
    "jg-dimensions-6": "0.375rem",
    "jg-dimensions-8": "0.5rem",
    "jg-dimensions-10": "0.625rem",
    "jg-dimensions-12": "0.75rem",
    "jg-dimensions-14": "0.875rem",
    "jg-dimensions-16": "1rem",
    "jg-dimensions-18": "1.125rem",
    "jg-dimensions-20": "1.25rem",
    "jg-dimensions-24": "1.5rem",
    "jg-dimensions-28": "1.75rem",
    "jg-dimensions-32": "2rem",
    "jg-dimensions-36": "2.25rem",
    "jg-dimensions-40": "2.5rem",
    "jg-dimensions-44": "2.75rem",
    "jg-dimensions-48": "3rem",
    "jg-dimensions-56": "3.5rem",
    "jg-dimensions-64": "4rem",
    "jg-dimensions-80": "5rem",
    "jg-dimensions-96": "6rem",
    "jg-dimensions-112": "7rem",
    "jg-dimensions-128": "8rem",
    "jg-dimensions-144": "9rem",
    "jg-dimensions-160": "10rem",
    "jg-dimensions-176": "11rem",
    "jg-dimensions-192": "12rem",
    "jg-dimensions-208": "13rem",
    "jg-dimensions-224": "14rem",
    "jg-dimensions-240": "15rem",
    "jg-dimensions-256": "16rem",
    "jg-dimensions-288": "18rem",
    "jg-dimensions-320": "20rem",
    "jg-dimensions-384": "24rem",
  },
  semanticTokens: {
    colors: {
      "chakra-body-text": { _light: "gray.800", _dark: "whiteAlpha.900" },
      "chakra-body-bg": { _light: "white", _dark: "gray.800" },
      "chakra-border-color": { _light: "gray.200", _dark: "whiteAlpha.300" },
      "chakra-inverse-text": { _light: "white", _dark: "gray.800" },
      "chakra-subtle-bg": { _light: "gray.100", _dark: "gray.700" },
      "chakra-subtle-text": { _light: "gray.600", _dark: "gray.400" },
      "chakra-placeholder-color": {
        _light: "gray.500",
        _dark: "whiteAlpha.400",
      },

      "jg-color-bg-bg": {
        _light: "jg-color-green-100",
        _dark: "jg-color-neutral-950",
      },
      "jg-color-bg-elevated": {
        _light: "jg-color-neutral-800",
        _dark: "jg-color-neutral-800",
      },
      "jg-color-bg-popover": "#262626f0",
      "jg-color-bg-strong": {
        _light: "jg-color-neutral-700",
        _dark: "jg-color-neutral-700",
      },
      "jg-color-bg-subtle": {
        _light: "jg-color-neutral-900",
        _dark: "jg-color-neutral-900",
      },
      "jg-color-bg-tooltip": "#404040f0",
      "jg-color-bg-button-primary-green": {
        _light: "jg-color-green-100",
        _dark: "jg-color-green-100",
      },
      "jg-color-bg-button-primary-green-disable": {
        _light: "jg-color-green-400",
        _dark: "jg-color-green-400",
      },
      "jg-color-bg-button-primary-green-hover": {
        _light: "jg-color-green-50",
        _dark: "jg-color-green-50",
      },
      "jg-color-bg-button-primary-red": {
        _light: "jg-color-red-100",
        _dark: "jg-color-red-100",
      },
      "jg-color-bg-button-primary-red-disable": {
        _light: "jg-color-red-400",
        _dark: "jg-color-red-400",
      },
      "jg-color-bg-button-primary-red-hover": {
        _light: "jg-color-red-50",
        _dark: "jg-color-red-50",
      },
      "jg-color-bg-button-primary-yellow": {
        _light: "jg-color-yellow-100",
        _dark: "jg-color-yellow-100",
      },
      "jg-color-bg-button-primary-yellow-disable": {
        _light: "jg-color-yellow-400",
        _dark: "jg-color-yellow-400",
      },
      "jg-color-bg-button-primary-yellow-hover": {
        _light: "jg-color-yellow-50",
        _dark: "jg-color-yellow-50",
      },
      "jg-color-bg-button-warning": {
        _light: "jg-color-yellow-400",
        _dark: "jg-color-yellow-400",
      },
      "jg-color-bg-input-default": {
        _light: "jg-color-white-alpha-4",
        _dark: "jg-color-white-alpha-4",
      },
      "jg-color-bg-input-disable": {
        _light: "jg-color-neutral-900",
        _dark: "jg-color-neutral-900",
      },
      "jg-color-bg-input-focused": {
        _light: "jg-color-white-alpha-2",
        _dark: "jg-color-white-alpha-2",
      },
      "jg-color-bg-tab-default": {
        _light: "jg-color-white-alpha-4",
        _dark: "jg-color-white-alpha-4",
      },
      "jg-color-bg-tab-selected-green": "#0a4c2280",
      "jg-color-bg-tab-selected-red": "#661c2ecc",
      "jg-color-bg-table-list-hover-1": {
        _light: "jg-color-white-alpha-4",
        _dark: "jg-color-white-alpha-4",
      },
      "jg-color-bg-table-list-hover-2": {
        _light: "jg-color-white-alpha-8",
        _dark: "jg-color-white-alpha-8",
      },
      "jg-color-border-split-muted": {
        _light: "jg-color-neutral-900",
        _dark: "jg-color-neutral-900",
      },
      "jg-color-border-split-strong": "#40404080",
      "jg-color-border-button-outline": {
        _light: "jg-color-white-alpha-16",
        _dark: "jg-color-white-alpha-16",
      },
      "jg-color-border-button-outline-hover": {
        _light: "jg-color-neutral-400",
        _dark: "jg-color-neutral-400",
      },
      "jg-color-border-button-secondary": {
        _light: "jg-color-green-300",
        _dark: "jg-color-green-300",
      },
      "jg-color-border-button-secondary-hover": {
        _light: "jg-color-green-100",
        _dark: "jg-color-green-100",
      },
      "jg-color-border-input-default": {
        _light: "jg-color-neutral-800",
        _dark: "jg-color-neutral-800",
      },
      "jg-color-border-input-focused": {
        _light: "jg-color-green-300",
        _dark: "jg-color-green-300",
      },
      "jg-color-border-input-hover": {
        _light: "jg-color-white-alpha-4",
        _dark: "jg-color-white-alpha-4",
      },
      "jg-color-border-input-wrong": {
        _light: "jg-color-yellow-200",
        _dark: "jg-color-yellow-200",
      },
      "jg-color-icon-disable": {
        _light: "jg-color-neutral-600",
        _dark: "jg-color-neutral-600",
      },
      "jg-color-icon-general": {
        _light: "jg-color-neutral-500",
        _dark: "jg-color-neutral-500",
      },
      "jg-color-icon-green-default": {
        _light: "jg-color-green-100",
        _dark: "jg-color-green-100",
      },
      "jg-color-icon-green-disable": {
        _light: "jg-color-green-300",
        _dark: "jg-color-green-300",
      },
      "jg-color-icon-green-subtle": {
        _light: "jg-color-green-200",
        _dark: "jg-color-green-200",
      },
      "jg-color-icon-info": {
        _light: "jg-color-icon-general",
        _dark: "jg-color-icon-general",
      },
      "jg-color-icon-primary": {
        _light: "jg-color-neutral-300",
        _dark: "jg-color-neutral-300",
      },
      "jg-color-icon-red": {
        _light: "jg-color-red-100",
        _dark: "jg-color-red-100",
      },
      "jg-color-icon-warning": {
        _light: "jg-color-yellow-100",
        _dark: "jg-color-yellow-100",
      },
      "jg-color-text-black": {
        _light: "jg-color-neutral-950",
        _dark: "jg-color-neutral-950",
      },
      "jg-color-text-hight-light": {
        _light: "jg-color-neutral-50",
        _dark: "jg-color-neutral-50",
      },
      "jg-color-text-primary": {
        _light: "jg-color-neutral-300",
        _dark: "jg-color-neutral-300",
      },
      "jg-color-text-red-default": {
        _light: "jg-color-red-100",
        _dark: "jg-color-red-100",
      },
      "jg-color-text-red-disable": {
        _light: "jg-color-red-300",
        _dark: "jg-color-red-300",
      },
      "jg-color-text-scendary": {
        _light: "jg-color-neutral-500",
        _dark: "jg-color-neutral-500",
      },
      "jg-color-text-tooltip": {
        _light: "jg-color-neutral-600",
        _dark: "jg-color-neutral-600",
      },
      "jg-color-text-green-default": {
        _light: "jg-color-green-100",
        _dark: "jg-color-green-100",
      },
      "jg-color-text-green-disable": {
        _light: "jg-color-green-300",
        _dark: "jg-color-green-300",
      },
      "jg-color-text-green-subtle": {
        _light: "jg-color-green-200",
        _dark: "jg-color-green-200",
      },
      "jg-color-text-yellow-default": {
        _light: "jg-color-yellow-100",
        _dark: "jg-color-yellow-100",
      },
      "jg-color-text-yellow-disable": {
        _light: "jg-color-yellow-300",
        _dark: "jg-color-yellow-300",
      },
    },
    spacing: {
      "jg-opacity-94": "var(--jg-opacity-94)",
      "jg-radius-sm": "var(--jg-radius-sm)",
      "jg-radius-md": "var(--jg-radius-md)",
      "jg-radius-lg": "var(--jg-radius-lg)",
    },
  },
});

export default theme;
